
package edu.cwru.nashua.pathwaysservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PathwaysServiceSoapMetabolomics", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
public interface PathwaysServiceSoapMetabolomics {
    /**
     * Returns a list of all pathways.
     * 
     * @return
     *     returns edu.cwru.nashua.pathwaysservice.ArrayOfSoapPathway
     */
    @WebMethod(operationName = "AllPathways", action = "http://nashua.cwru.edu/PathwaysService/AllPathways")
    @WebResult(name = "AllPathwaysResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "AllPathways", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.AllPathways")
    @ResponseWrapper(localName = "AllPathwaysResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.AllPathwaysResponse")
    public ArrayOfSoapPathway allPathways();

    /**
     * Returns a string representing the organism hierarchy in XML.
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOrganismHierarchy", action = "http://nashua.cwru.edu/PathwaysService/GetOrganismHierarchy")
    @WebResult(name = "GetOrganismHierarchyResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetOrganismHierarchy", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetOrganismHierarchy")
    @ResponseWrapper(localName = "GetOrganismHierarchyResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetOrganismHierarchyResponse")
    public String getOrganismHierarchy();

    /**
     * Returns a single pathway by id.
     * 
     * @param id
     * @return
     *     returns edu.cwru.nashua.pathwaysservice.SoapPathway
     */
    @WebMethod(operationName = "GetPathway", action = "http://nashua.cwru.edu/PathwaysService/GetPathway")
    @WebResult(name = "GetPathwayResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetPathway", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetPathway")
    @ResponseWrapper(localName = "GetPathwayResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetPathwayResponse")
    public SoapPathway getPathway(
        @WebParam(name = "id", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String id);


     /**
     * Returns Compartment.
     *
     * @param id
     * @return
     *     returns edu.cwru.nashua.pathwaysservice.SoapPathway
     */
    @WebMethod(operationName = "GetCompartment", action = "http://nashua.cwru.edu/PathwaysService/GetCompartment")
    @WebResult(name = "GetCompartmentResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetCompartment", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetCompartment")
    @ResponseWrapper(localName = "GetCompartmentResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetCompartmentResponse")
    public SoapCompartment getCompartment(
        @WebParam(name = "id", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String id);


    /**
     * Returns sub Compartments.
     *
     * @param id
     * @return
     *     returns edu.cwru.nashua.pathwaysservice.SoapPathway
     */
    @WebMethod(operationName = "GetImmediateChildren", action = "http://nashua.cwru.edu/PathwaysService/GetImmediateChildren")
    @WebResult(name = "GetImmediateChildrenResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetImmediateChildren", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetImmediateChildren")
    @ResponseWrapper(localName = "GetImmediateChildrenResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetImmediateChildrenResponse")
    public ArrayOfSoapCompartment getImmediateChildren(
        @WebParam(name = "id", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String id);

    /**
     * Returns a list of all processes.
     * 
     * @return
     *     returns edu.cwru.nashua.pathwaysservice.ArrayOfSoapProcess
     */
    @WebMethod(operationName = "AllProcesses", action = "http://nashua.cwru.edu/PathwaysService/AllProcesses")
    @WebResult(name = "AllProcessesResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "AllProcesses", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.AllProcesses")
    @ResponseWrapper(localName = "AllProcessesResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.AllProcessesResponse")
    public ArrayOfSoapProcess allProcesses();

    /**
     * Get data required to render a graph displaying the given set of objects and their interactions.  Each parameter accepts a semi-colon delimited list of object GUIDs of the appropriate type (or an empty string).
     * 
     * @param expandedPathwayGuids
     * @param moleculeGuids
     * @param genericProcessGuids
     * @param collapsedPathwayGuids
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetGraphData", action = "http://nashua.cwru.edu/PathwaysService/GetGraphData")
    @WebResult(name = "GetGraphDataResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetGraphData", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGraphData")
    @ResponseWrapper(localName = "GetGraphDataResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGraphDataResponse")
    public String getGraphData(
        @WebParam(name = "collapsedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String collapsedPathwayGuids,
        @WebParam(name = "expandedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String expandedPathwayGuids,
        @WebParam(name = "genericProcessGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String genericProcessGuids,
        @WebParam(name = "moleculeGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String highlightGuids,
        @WebParam(name = "highlights", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String highlights);

    /**
     * Get data required to render a graph displaying the given set of objects and their interactions.  Each parameter accepts a semi-colon delimited list of object GUIDs of the appropriate type (or an empty string).
     *
     * @param modelId
     * @return
     *     returns java.lang.String
    */
    @WebMethod(operationName = "GetSBModelByID", action = "http://nashua.cwru.edu/PathwaysService/GetSBModelByID")
    @WebResult(name = "GetSBModelByIDResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetSBModelByID", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetSBModelByID")
    @ResponseWrapper(localName = "GetSBModelByIDResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetSBModelByIDResponse")
    public String getSBModelByID(
        @WebParam(name = "modelId", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String modelId,
        @WebParam(name = "testmodelId", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String testmodelId);

    /**
     * Get data required to render a graph displaying the given set of objects and their interactions ONLY From the SELECTED TISSUES.  Each parameter accepts a semi-colon delimited list of object GUIDs of the appropriate type (or an empty string).
     * 
     * @param expandedPathwayGuids
     * @param moleculeGuids
     * @param genericProcessGuids
     * @param collapsedPathwayGuids
     * @param tissues
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSelectedTissueGraphData", action = "http://nashua.cwru.edu/PathwaysService/GetSelectedTissueGraphData")
    @WebResult(name = "GetSelectedTissueGraphDataResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetSelectedTissueGraphData", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetSelectedTissueGraphData")
    @ResponseWrapper(localName = "GetSelectedTissueGraphDataResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetSelectedTissueGraphDataResponse")
    public String getSelectedTissueGraphData(
        @WebParam(name = "collapsedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String collapsedPathwayGuids,
        @WebParam(name = "expandedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String expandedPathwayGuids,
        @WebParam(name = "genericProcessGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String genericProcessGuids,
        @WebParam(name = "moleculeGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String moleculeGuids,
        @WebParam(name = "tissues", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String tissues);

    /**
     * retrieve the whole layout information of a specific pathway
     * 
     * @param expandedPathwayGuids
     * @param moleculeGuids
     * @param genericProcessGuids
     * @param collapsedPathwayGuids
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveLayout", action = "http://nashua.cwru.edu/PathwaysService/RetrieveLayout")
    @WebResult(name = "RetrieveLayoutResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "RetrieveLayout", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.RetrieveLayout")
    @ResponseWrapper(localName = "RetrieveLayoutResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.RetrieveLayoutResponse")
    public String retrieveLayout(
        @WebParam(name = "collapsedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String collapsedPathwayGuids,
        @WebParam(name = "expandedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String expandedPathwayGuids,
        @WebParam(name = "genericProcessGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String genericProcessGuids,
        @WebParam(name = "moleculeGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String moleculeGuids);

    /**
     * save the whole layout information of a specific pathway
     * 
     * @param expandedPathwayGuids
     * @param moleculeGuids
     * @param layout
     * @param genericProcessGuids
     * @param collapsedPathwayGuids
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "StoreLayout", action = "http://nashua.cwru.edu/PathwaysService/StoreLayout")
    @WebResult(name = "StoreLayoutResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "StoreLayout", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.StoreLayout")
    @ResponseWrapper(localName = "StoreLayoutResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.StoreLayoutResponse")
    public boolean storeLayout(
        @WebParam(name = "collapsedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String collapsedPathwayGuids,
        @WebParam(name = "expandedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String expandedPathwayGuids,
        @WebParam(name = "genericProcessGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String genericProcessGuids,
        @WebParam(name = "moleculeGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String moleculeGuids,
        @WebParam(name = "layout", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String layout,
        @WebParam(name = "key", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String key);

    /**
     * Returns the set of organisms that have at least one mapped gene encoding an enzyme of a pathway in a given set of comma separated pathways.
     * 
     * @param pathwayIdSet
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetGenomesForPathways", action = "http://nashua.cwru.edu/PathwaysService/GetGenomesForPathways")
    @WebResult(name = "GetGenomesForPathwaysResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetGenomesForPathways", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGenomesForPathways")
    @ResponseWrapper(localName = "GetGenomesForPathwaysResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGenomesForPathwaysResponse")
    public String getGenomesForPathways(
        @WebParam(name = "pathwayIdSet", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String pathwayIdSet);

    /**
     * Returns the set of genes that encode the enzymes of a given pathway.
     * 
     * @param pathwayId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetGeneMappingForPathway", action = "http://nashua.cwru.edu/PathwaysService/GetGeneMappingForPathway")
    @WebResult(name = "GetGeneMappingForPathwayResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetGeneMappingForPathway", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGeneMappingForPathway")
    @ResponseWrapper(localName = "GetGeneMappingForPathwayResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGeneMappingForPathwayResponse")
    public String getGeneMappingForPathway(
        @WebParam(name = "pathwayId", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String pathwayId);

    /**
     * Returns the set of genes that encode the enzymes of a given list of comma-separated pathways in an organism.
     * 
     * @param organismGroupId
     * @param pathwayIdSet
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetGeneMappingForOrganismPathways", action = "http://nashua.cwru.edu/PathwaysService/GetGeneMappingForOrganismPathways")
    @WebResult(name = "GetGeneMappingForOrganismPathwaysResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetGeneMappingForOrganismPathways", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGeneMappingForOrganismPathways")
    @ResponseWrapper(localName = "GetGeneMappingForOrganismPathwaysResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGeneMappingForOrganismPathwaysResponse")
    public String getGeneMappingForOrganismPathways(
        @WebParam(name = "pathwayIdSet", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String pathwayIdSet,
        @WebParam(name = "organismGroupId", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String organismGroupId);

}
