
package edu.cwru.nashua.pathwaysservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PathwaysService", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", wsdlLocation ="http://dblab.case.edu/PathwaysService/pathwaysservice.asmx?WSDL") 
public class PathwaysService
    extends Service
{

    private final static URL PATHWAYSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://dblab.case.edu/PathwaysServiceSB/pathwaysservice.asmx?WSDL");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PATHWAYSSERVICE_WSDL_LOCATION = url;
    }

    public PathwaysService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PathwaysService() {
        super(PATHWAYSSERVICE_WSDL_LOCATION, new QName("http://nashua.cwru.edu/PathwaysService/", "PathwaysService"));
    }

    /**
     * 
     * @return
     *     returns PathwaysServiceSoap
     */
    @WebEndpoint(name = "PathwaysServiceSoap")
    public PathwaysServiceSoap getPathwaysServiceSoap() {
        return (PathwaysServiceSoap)super.getPort(new QName("http://nashua.cwru.edu/PathwaysService/", "PathwaysServiceSoap"), PathwaysServiceSoap.class);
    }

    //added by mustafa
    public PathwaysService (URL wsdlLocation)
    {
        super(wsdlLocation, new QName("http://nashua.cwru.edu/PathwaysService/", "PathwaysService"));
    }

    //added by mustafa
    public PathwaysService (String wsdlLocation) throws MalformedURLException
    {
        super(new URL(wsdlLocation), new QName("http://nashua.cwru.edu/PathwaysService/", "PathwaysService"));
    }

}
