
package edu.cwru.nashua.pathwaysservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PathwaysServiceSoap", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
public interface PathwaysServiceSoap {


    /**
     * Log a user in to enable editing.
     * 
     * @param name
     * @param password
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Login", action = "http://nashua.cwru.edu/PathwaysService/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.LoginResponse")
    public boolean login(
        @WebParam(name = "name", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String name,
        @WebParam(name = "password", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String password);

    /**
     * Log the user out.
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Logout", action = "http://nashua.cwru.edu/PathwaysService/Logout")
    @WebResult(name = "LogoutResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.LogoutResponse")
    public boolean logout();

    /**
     * Returns the name of the currently logged in user.
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CurrentUser", action = "http://nashua.cwru.edu/PathwaysService/CurrentUser")
    @WebResult(name = "CurrentUserResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "CurrentUser", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.CurrentUser")
    @ResponseWrapper(localName = "CurrentUserResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.CurrentUserResponse")
    public String currentUser();

    /**
     * Returns the web service version.
     * 
     * @return
     *     returns java.lang.String
     */
//    @WebMethod(operationName = "Version", action = "http://nashua.cwru.edu/PathwaysService/Version")
//    @WebResult(name = "VersionResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
//    @RequestWrapper(localName = "Version", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.Version")
//    @ResponseWrapper(localName = "VersionResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.VersionResponse")
//    public String version();

    /**
     * Returns a list of all pathways.
     * 
     * @return
     *     returns edu.cwru.nashua.pathwaysservice.ArrayOfSoapPathway
     */
    @WebMethod(operationName = "AllPathways", action = "http://nashua.cwru.edu/PathwaysService/AllPathways")
    @WebResult(name = "AllPathwaysResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "AllPathways", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.AllPathways")
    @ResponseWrapper(localName = "AllPathwaysResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.AllPathwaysResponse")
    public ArrayOfSoapPathway allPathways();

    /**
     * Returns a string representing the organism hierarchy in XML.
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOrganismHierarchy", action = "http://nashua.cwru.edu/PathwaysService/GetOrganismHierarchy")
    @WebResult(name = "GetOrganismHierarchyResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetOrganismHierarchy", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetOrganismHierarchy")
    @ResponseWrapper(localName = "GetOrganismHierarchyResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetOrganismHierarchyResponse")
    public String getOrganismHierarchy();

    /**
     * Returns a single pathway by id.
     * 
     * @param id
     * @return
     *     returns edu.cwru.nashua.pathwaysservice.SoapPathway
     */
    @WebMethod(operationName = "GetPathway", action = "http://nashua.cwru.edu/PathwaysService/GetPathway")
    @WebResult(name = "GetPathwayResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetPathway", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetPathway")
    @ResponseWrapper(localName = "GetPathwayResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetPathwayResponse")
    public SoapPathway getPathway(
        @WebParam(name = "id", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String id);

    /**
     * Returns a list of all processes.
     * 
     * @return
     *     returns edu.cwru.nashua.pathwaysservice.ArrayOfSoapProcess
     */
    @WebMethod(operationName = "AllProcesses", action = "http://nashua.cwru.edu/PathwaysService/AllProcesses")
    @WebResult(name = "AllProcessesResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "AllProcesses", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.AllProcesses")
    @ResponseWrapper(localName = "AllProcessesResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.AllProcessesResponse")
    public ArrayOfSoapProcess allProcesses();

    /**
     * Save changes to a pathway. Requires login.
     * 
     * @param pathway
     * @return
     *     returns edu.cwru.nashua.pathwaysservice.SoapPathway
     */
    @WebMethod(operationName = "SavePathway", action = "http://nashua.cwru.edu/PathwaysService/SavePathway")
    @WebResult(name = "SavePathwayResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "SavePathway", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.SavePathway")
    @ResponseWrapper(localName = "SavePathwayResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.SavePathwayResponse")
    public SoapPathway savePathway(
        @WebParam(name = "pathway", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        SoapPathway pathway);

    /**
     * Get data required to render a graph displaying the given set of objects and their interactions.  Each parameter accepts a semi-colon delimited list of object GUIDs of the appropriate type (or an empty string).
     * 
     * @param expandedPathwayGuids
     * @param moleculeGuids
     * @param genericProcessGuids
     * @param collapsedPathwayGuids
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetGraphData", action = "http://nashua.cwru.edu/PathwaysService/GetGraphData")
    @WebResult(name = "GetGraphDataResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetGraphData", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGraphData")
    @ResponseWrapper(localName = "GetGraphDataResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGraphDataResponse")
    public String getGraphData(
        @WebParam(name = "collapsedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String collapsedPathwayGuids,
        @WebParam(name = "expandedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String expandedPathwayGuids,
        @WebParam(name = "genericProcessGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String genericProcessGuids,
        @WebParam(name = "moleculeGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String moleculeGuids,
        @WebParam(name = "collapsedModelids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String collapsedModelids,
        @WebParam(name = "expandedModelGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String expandedModelGuids,
        @WebParam(name = "reactionGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String reactionGuids,
        @WebParam(name = "speciesGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String speciesGuids);

   /**
     * Get data required to render a graph displaying the given set of objects and their interactions.  Each parameter accepts a semi-colon delimited list of object GUIDs of the appropriate type (or an empty string).
     *
     * @param modelId
     * @return
     *     returns java.lang.String
    */
    @WebMethod(operationName = "GetSBModelByID", action = "http://nashua.cwru.edu/PathwaysService/GetSBModelByID")
    @WebResult(name = "GetSBModelByIDResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetSBModelByID", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetSBModelByID")
    @ResponseWrapper(localName = "GetSBModelByIDResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetSBModelByIDResponse")
    public String GetSBModelByID(
        @WebParam(name = "modelId", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String modelId);

    /**
     * Get data required to render a graph displaying the given set of objects and their interactions ONLY From the SELECTED TISSUES.  Each parameter accepts a semi-colon delimited list of object GUIDs of the appropriate type (or an empty string).
     *
     * @param expandedPathwayGuids
     * @param moleculeGuids
     * @param genericProcessGuids
     * @param collapsedPathwayGuids
     * @param tissues
     * @return
     *     returns java.lang.String
     */
//    @WebMethod(operationName = "GetSelectedTissueGraphData", action = "http://nashua.cwru.edu/PathwaysService/GetSelectedTissueGraphData")
//    @WebResult(name = "GetSelectedTissueGraphDataResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
//    @RequestWrapper(localName = "GetSelectedTissueGraphData", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetSelectedTissueGraphData")
//    @ResponseWrapper(localName = "GetSelectedTissueGraphDataResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetSelectedTissueGraphDataResponse")
//    public String getSelectedTissueGraphData(
//        @WebParam(name = "collapsedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
//        String collapsedPathwayGuids,
//        @WebParam(name = "expandedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
//        String expandedPathwayGuids,
//        @WebParam(name = "genericProcessGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
//        String genericProcessGuids,
//        @WebParam(name = "moleculeGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
//        String moleculeGuids,
//        @WebParam(name = "tissues", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
//        String tissues);


    /**
     * save the whole layout information of a specific pathway
     * 
     * @param expandedPathwayGuids
     * @param moleculeGuids
     * @param layout
     * @param genericProcessGuids
     * @param collapsedPathwayGuids
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "StoreLayout", action = "http://nashua.cwru.edu/PathwaysService/StoreLayout")
    @WebResult(name = "StoreLayoutResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "StoreLayout", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.StoreLayout")
    @ResponseWrapper(localName = "StoreLayoutResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.StoreLayoutResponse")
    public boolean storeLayout(
        @WebParam(name = "collapsedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String collapsedPathwayGuids,
        @WebParam(name = "expandedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String expandedPathwayGuids,
        @WebParam(name = "genericProcessGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String genericProcessGuids,
        @WebParam(name = "moleculeGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String moleculeGuids,
        @WebParam(name = "layout", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String layout);

    @WebMethod(operationName = "StoreLayout", action = "http://nashua.cwru.edu/PathwaysService/StoreLayout")
    @WebResult(name = "StoreLayoutResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "StoreLayout", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.StoreLayout")
    @ResponseWrapper(localName = "StoreLayoutResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.StoreLayoutResponse")
    public boolean storeLayout2(
        @WebParam(name = "collapsedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String collapsedPathwayGuids,
        @WebParam(name = "expandedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String expandedPathwayGuids,
        @WebParam(name = "genericProcessGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String genericProcessGuids,
        @WebParam(name = "moleculeGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String moleculeGuids,
        @WebParam(name = "layout", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String layout,
        @WebParam(name = "key", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String key);


        /**
     * Get data required to render a graph displaying the given set of objects and their interactions ONLY From the SELECTED TISSUES.  Each parameter accepts a semi-colon delimited list of object GUIDs of the appropriate type (or an empty string).
     *
     * @param expandedPathwayGuids
     * @param moleculeGuids
     * @param genericProcessGuids
     * @param collapsedPathwayGuids
     * @param tissues
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSelectedTissueGraphData", action = "http://nashua.cwru.edu/PathwaysService/GetSelectedTissueGraphData")
    @WebResult(name = "GetSelectedTissueGraphDataResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetSelectedTissueGraphData", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetSelectedTissueGraphData")
    @ResponseWrapper(localName = "GetSelectedTissueGraphDataResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetSelectedTissueGraphDataResponse")
    public String getSelectedTissueGraphData(
        @WebParam(name = "collapsedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String collapsedPathwayGuids,
        @WebParam(name = "expandedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String expandedPathwayGuids,
        @WebParam(name = "genericProcessGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String genericProcessGuids,
        @WebParam(name = "moleculeGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String moleculeGuids,
        @WebParam(name = "tissues", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String tissues);

    /**
     * retrieve the whole layout information of a specific pathway
     * 
     * @param expandedPathwayGuids
     * @param moleculeGuids
     * @param genericProcessGuids
     * @param collapsedPathwayGuids
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveLayout", action = "http://nashua.cwru.edu/PathwaysService/RetrieveLayout")
    @WebResult(name = "RetrieveLayoutResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "RetrieveLayout", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.RetrieveLayout")
    @ResponseWrapper(localName = "RetrieveLayoutResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.RetrieveLayoutResponse")
    public String retrieveLayout(
        @WebParam(name = "collapsedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String collapsedPathwayGuids,
        @WebParam(name = "expandedPathwayGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String expandedPathwayGuids,
        @WebParam(name = "genericProcessGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String genericProcessGuids,
        @WebParam(name = "moleculeGuids", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String moleculeGuids);

    /**
     * Generate a graph for processes no more than N steps away from a given process.
     * 
     * @param organismGroupName
     * @param processId
     * @param step
     * @return
     *     returns edu.cwru.nashua.pathwaysservice.ArrayOfSoapProcess
     */
    @WebMethod(operationName = "ProcessNeighborhood", action = "http://nashua.cwru.edu/PathwaysService/ProcessNeighborhood")
    @WebResult(name = "ProcessNeighborhoodResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "ProcessNeighborhood", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.ProcessNeighborhood")
    @ResponseWrapper(localName = "ProcessNeighborhoodResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.ProcessNeighborhoodResponse")
    public ArrayOfSoapProcess processNeighborhood(
        @WebParam(name = "processId", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String processId,
        @WebParam(name = "organismGroupName", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String organismGroupName,
        @WebParam(name = "step", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        int step);

    /**
     * Returns the appropriate URL to the specified page.
     * 
     * @param displayItemID
     * @param openNode2Type
     * @param openSection
     * @param openNode3ID
     * @param openNode2ID
     * @param displayItemType
     * @param openNode3Type
     * @param openNode1ID
     * @param openNode1Type
     * @param organism
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MakeLinkToPage", action = "http://nashua.cwru.edu/PathwaysService/MakeLinkToPage")
    @WebResult(name = "MakeLinkToPageResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "MakeLinkToPage", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.MakeLinkToPage")
    @ResponseWrapper(localName = "MakeLinkToPageResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.MakeLinkToPageResponse")
    public String makeLinkToPage(
        @WebParam(name = "openSection", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String openSection,
        @WebParam(name = "organism", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String organism,
        @WebParam(name = "openNode1ID", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String openNode1ID,
        @WebParam(name = "openNode1Type", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String openNode1Type,
        @WebParam(name = "openNode2ID", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String openNode2ID,
        @WebParam(name = "openNode2Type", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String openNode2Type,
        @WebParam(name = "openNode3ID", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String openNode3ID,
        @WebParam(name = "openNode3Type", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String openNode3Type,
        @WebParam(name = "displayItemID", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String displayItemID,
        @WebParam(name = "displayItemType", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String displayItemType);

    /**
     * Returns the set of organisms that have at least one mapped gene encoding an enzyme of a given pathway
     * 
     * @param pathwayId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetGenomesForPathway", action = "http://nashua.cwru.edu/PathwaysService/GetGenomesForPathway")
    @WebResult(name = "GetGenomesForPathwayResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetGenomesForPathway", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGenomesForPathway")
    @ResponseWrapper(localName = "GetGenomesForPathwayResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGenomesForPathwayResponse")
    public String getGenomesForPathway(
        @WebParam(name = "pathwayId", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String pathwayId);

    @WebMethod(operationName = "GetGenomesForPathways", action = "http://nashua.cwru.edu/PathwaysService/GetGenomesForPathways")
    @WebResult(name = "GetGenomesForPathwaysResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetGenomesForPathways", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGenomesForPathways")
    @ResponseWrapper(localName = "GetGenomesForPathwaysResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGenomesForPathwaysResponse")
     public String getGenomesForPathways(
        @WebParam(name = "pathwayIdSet", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String pathwayIdSet);

    /**
     * Returns the set of genes that encodes the enzymes of a given pathway.
     * 
     * @param pathwayId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetGeneMappingForPathway", action = "http://nashua.cwru.edu/PathwaysService/GetGeneMappingForPathway")
    @WebResult(name = "GetGeneMappingForPathwayResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetGeneMappingForPathway", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGeneMappingForPathway")
    @ResponseWrapper(localName = "GetGeneMappingForPathwayResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGeneMappingForPathwayResponse")
    public String getGeneMappingForPathway(
        @WebParam(name = "pathwayId", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String pathwayId);

    /**
     * Returns the set of genes that encodes the enzymes of a given pathway in an organism.
     * 
     * @param organismGroupId
     * @param pathwayId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetGeneMappingForOrganismPathway", action = "http://nashua.cwru.edu/PathwaysServicesb/GetGeneMappingForOrganismPathway")
    @WebResult(name = "GetGeneMappingForOrganismPathwayResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetGeneMappingForOrganismPathway", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGeneMappingForOrganismPathway")
    @ResponseWrapper(localName = "GetGeneMappingForOrganismPathwayResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGeneMappingForOrganismPathwayResponse")
    public String getGeneMappingForOrganismPathway(
        @WebParam(name = "pathwayId", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String pathwayId,
        @WebParam(name = "organismGroupId", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String organismGroupId);

    @WebMethod(operationName = "GetGeneMappingForOrganismPathways", action = "http://nashua.cwru.edu/PathwaysService/GetGeneMappingForOrganismPathways")
    @WebResult(name = "GetGeneMappingForOrganismPathwaysResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "GetGeneMappingForOrganismPathways", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGeneMappingForOrganismPathways")
    @ResponseWrapper(localName = "GetGeneMappingForOrganismPathwaysResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.GetGeneMappingForOrganismPathwaysResponse")
    public String getGeneMappingForOrganismPathways(
        @WebParam(name = "pathwayIdSet", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String pathwayIdSet,
        @WebParam(name = "organismGroupId", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String organismGroupId);
       
//    /**
//     * Insert a bug to the bug database.
//     */
    @WebMethod(operationName = "InsertBug", action = "http://nashua.cwru.edu/PathwaysService/InsertBug")
    @WebResult(name = "InsertBugResult", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
    @RequestWrapper(localName = "InsertBug", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.InsertBug")
    @ResponseWrapper(localName = "InsertBugResponse", targetNamespace = "http://nashua.cwru.edu/PathwaysService/", className = "edu.cwru.nashua.pathwaysservice.InsertBugResponse")
    public int insertBug(
        @WebParam(name = "description", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String description,
        @WebParam(name = "callHierarchy", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String callHierarchy,
        @WebParam(name = "firstName", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String lastName,
        @WebParam(name = "eMail", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String eMail,
        @WebParam(name = "phone", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String phone,
        @WebParam(name = "severity", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        byte severity,
        @WebParam(name = "bugType", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        byte bugType,
        @WebParam(name = "bugTypeOther", targetNamespace = "http://nashua.cwru.edu/PathwaysService/")
        String bugTypeOther);   
}
